### ISSUE TITLE
Support for WLAN adapter AP-WB2E (UTY-TFNXZ1)

### ISSUE THREAD

**Issue by Mysteoa** [bigmoby/fglair_for_homeassistant#120]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I have a second AC model AGHG09LVCA with WLAN adapter AP-WB2E (UTY-TFNXZ1). I can see both of my AC in the FGLair app and control them, but only one of them shows up with this integration. I would like to have both of them show up in Home Assistant.

### Describe alternatives you've considered

I did try to use this integration initially https://github.com/deiger/AirCon , but I'm not sure if there is an additional configuration needed. Because after I configured it, nothing showed up.

### Additional context

No

**Comment by bigmoby** [comment]
Hi @Mysteoa , I think the right solution is adopt this add-on https://github.com/deiger/AirCon 
Unfortunately I don't know the feature related your AC model.

**Comment by bigmoby** [comment]
I'm sorry I can't help you.
