### ISSUE TITLE
Cooling shows as heating

### ISSUE THREAD

**Issue by SgtFlippy** [bigmoby/fglair_for_homeassistant#126]
## System Information

version | core-2024.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 5.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | SharpTools.io (1.0.9), Mosquitto broker (6.4.0), Terminal & SSH (9.14.0), Samba share (12.3.1), Zigbee2MQTT (1.37.1-1), File editor (5.8.0), Matter Server (5.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 10
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 mei 2024 om 20:00
-- | --
current_recorder_run | 11 mei 2024 om 11:56
estimated_db_size | 152.79 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

So today I turned my AC actually on since a while and noticed an orange "heating" inside the thermostat tile instead of a blue "cooling".
Mode is set to cooling, changing it to heating makes it look the same. The ring is blue as it should.
![Screenshot_20240513_190030_Chrome](https://github.com/bigmoby/fglair_for_homeassistant/assets/97621135/35eccd33-c132-4696-be23-379b17a298e2)

### Reproduction steps

1. Turn the AC on and set to cooling
2.
3.
...

### Debug logs

```text
Nothing here
```

**Comment by Rydcal** [comment]
Seeing this on Dry mode too.

**Comment by andymk3** [comment]
Exact same issue here too.

**Comment by bigmoby** [comment]
Hi @SgtFlippy , have you tried to downgrade the fglair component version? So I could understand if it's related to a regression or not. Thanks

**Comment by SgtFlippy** [comment]
I'll try on a pc later, on my phone at the moment and it won't let me select an older version. It keeps reverting to 11

**Comment by brianup3** [comment]
I see the same issue and can confirm the issue starts after v0.3.9. Rolling back to v0.3.9 resolves the issue.

**Comment by bigmoby** [comment]
Does the problem occur only when changing the operational mode of the air conditioner via the remote control/mobile app, or does it also occur when making operational changes through the Home Assistant integration?

**Comment by SgtFlippy** [comment]
I only use the integration.
I just tried the remote and it acts the same.

**Comment by bigmoby** [comment]
ok thanks 👍

**Comment by bigmoby** [comment]
Ok, guys the bug is here: https://github.com/bigmoby/fglair_for_homeassistant/compare/v0.3.9...v0.3.11#diff-92f423a383836f29ab4da47d732b6c14acc19204ac4b0093e6af4fe1623d8d11R362
I have to understand how hvac_action param works and why, if defined, overrides its state in lovelace.

**Comment by bigmoby** [comment]
Hi guys,
https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.3.12 should fix this issue https://github.com/bigmoby/fglair_for_homeassistant/issues/126 

Thank you for using this custom component and for your support! As this project is maintained solely through my personal time and effort, contributions from the community are greatly appreciated. If you find this component useful, please consider contributing in any way you can to help improve and sustain the project. Thanks 🙏

**Comment by SgtFlippy** [comment]
That fixed it for me, thanks!
