### ISSUE TITLE
Current celcius temperature is showing the fahrenheit value

### ISSUE THREAD

**Issue by m4thieulavoie** [bigmoby/fglair_for_homeassistant#13]
Since the new update allowing to see the current value (nice!), I indeed see the value, but the fahrenheit one, even though it says `C` right beside of it.

I wonder if it has to do with the fact I am in Canada with the US config.

I'd love to PR a fix myself but am really unsure as to how to test this repo locally. Any help is welcome!

<img width="490" alt="image" src="https://user-images.githubusercontent.com/44816587/209857100-ac6a1424-8df8-4c57-9f1f-997cee7838e7.png">

My gut feeling is [this line](https://github.com/bigmoby/fglair_for_homeassistant/blob/main/custom_components/fglair_heatpump_controller/climate.py#L129) returns a fahrenheit value. I'm not sure where that comes from though as my FGLair account is all set in celcius

Thanks!

**Comment by chiefcomm** [comment]
Thanks @m4thieulavoie  this situation is similar to what I face in Australia.   My account is on the US server but I wanted Celsius displayed.  The way the config region works is it looks at the values 'cn' and 'eu" and chooses the China or Europe servers for logon.   Any other value defaults to the US server.  Therefore in Australia I use 'au' in the config and all works well, you woudl be able to test this theory by replacing 'us' with 'ca' in your config.

cn = https://ads-field.ayla.com.cn/apiv1/
eu = https://ads-field-eu.aylanetworks.com/apiv1/
else = https://ads-field.aylanetworks.com/apiv1/

````
climate:
  - platform: fglair_heatpump_controller
    username: !secret fglair_username
    password: !secret fglair_password
    region: 'ca'
    tokenpath: 'token.txt'

**Comment by m4thieulavoie** [comment]
Oh that's rad, I didn't realize that `region` could take more values. That worked 💪 I might open a PR updating the docs to publicize the other possible values 👍
