### ISSUE TITLE
WARNINGS on v2024.6.0

### ISSUE THREAD

**Issue by Korvenwin** [bigmoby/fglair_for_homeassistant#133]
## System Information

version | core-2024.6.0

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After update to v2024.6.0, the log show some warnings.

### Reproduction steps

1. Check log viewer

### Debug logs

```text
`2024-06-06 09:40:51.626 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'fglair_heatpump_controller' at custom_components/fglair_heatpump_controller/climate.py, line 414: self._properties = await self._fujitsu_device.async_update_properties() (offender: /usr/local/lib/python3.12/site-packages/pyfujitsugeneral/client.py, line 87: f = open(access_token_file, encoding="utf-8")), please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues`

`2024-06-06 09:40:52.070 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'fglair_heatpump_controller' at custom_components/fglair_heatpump_controller/climate.py, line 414: self._properties = await self._fujitsu_device.async_update_properties() (offender: /usr/local/lib/python3.12/site-packages/pyfujitsugeneral/client.py, line 181: with open(self._ACCESS_TOKEN_FILE, "w", encoding="utf-8") as f:), please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues`
```

**Comment by colino17** [comment]
I am also getting this error in my HA logs. I also noticed my server had a few system reboots that I couldn't explain. The journalctl logging of reboot reasons showed me the HA logs related to this component.

**Comment by Korvenwin** [comment]
In my case, everything works fine without any issue. Only warnings on log.

**Comment by bigmoby** [comment]
The release https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.3.13 should fix.
Thanks to @drc38 for fix 🙌

**Comment by Korvenwin** [comment]
THANK YOU VERY MUCH. Your great support is the cause why I've bought another Fujitsu Air conditioning equipment with FGLair support (although it appears that new models came with Airstage support).

**Comment by Korvenwin** [comment]
Hi, again.
Warnings are missing but now I receive an excpetion, although the integration appears to works fine:

`  File "/usr/local/lib/python3.12/site-packages/pyfujitsugeneral/client.py", line 238, in api_wrapper
    raise FGLairGeneralException from exception
pyfujitsugeneral.exceptions.FGLairGeneralException: FGLairBaseException has been raised`

**Comment by bigmoby** [comment]
Hi @Korvenwin how could I reproduce this exception? Please could you write a clear step by step procedure?

**Comment by Korvenwin** [comment]
I'm sorry, after operate with the equipment the exceptdion dissapeared and I haven't gotten it any more.

**Comment by bigmoby** [comment]
Ok no problem, thanks 👍
