### ISSUE TITLE
temperathure in app not the same as on HA

### ISSUE THREAD

**Issue by Yakie996** [bigmoby/fglair_for_homeassistant#15]
Hi,

The temperature in the app displays 18C and in HA it displays 20C and rarely updates.

Kind regards

**Comment by chiefcomm** [comment]
@Yakie996 please install version v0.1.4 and add the following to configuration.yaml.

````
logger:
  default: critical
  logs:
    custom_components.fglair_heatpump_controller.climate: debug
    homeassistant.components.climate: debug
````

I'm really interested in the lines below from your logs and the attributes from HA.

````
2023-01-13 07:39:14.484 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature json: {'value': 7500, 'key': 93872419}
2023-01-13 07:39:14.484 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature: 7500
2023-01-13 07:39:14.484 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Region: au
````
![image](https://user-images.githubusercontent.com/45157523/212199276-36ae0dcb-8bd4-4f84-989f-347386bf6de7.png)

**Comment by bigmoby** [comment]
Yes @chiefcomm also for me there's an offset of +2 celsius degree

**Comment by chiefcomm** [comment]
@bigmoby the API from where we extract the current temp does seems to report different data than the mobile app.  Can you confirm that the data in the logs is exactly the same as what shows in HA?

````
2023-01-14 09:31:59.611 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature json: {'value': 7400, 'key': 93872419}
2023-01-14 09:31:59.611 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature: 7400
2023-01-14 09:31:59.611 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Region: us
````
![image](https://user-images.githubusercontent.com/45157523/212431644-4fd41628-092c-41f6-879f-5144ed63269b.png)

**Comment by chiefcomm** [comment]
same again in Celsius
````
2023-01-14 09:45:12.479 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature json: {'value': 7400, 'key': 93872419}
2023-01-14 09:45:12.479 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature: 7400
2023-01-14 09:45:12.480 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Region: us
````
![image](https://user-images.githubusercontent.com/45157523/212432898-efaa5d2f-7d89-4af0-aa81-3bc64a6f1122.png)

![image](https://user-images.githubusercontent.com/45157523/212432950-d002d45c-c077-41c4-9721-42b2adace4c5.png)

**Comment by bigmoby** [comment]
Hi @chiefcomm ,
`current_temperature: 19.4`
and in the logs `Display_temperature json: {'value': 6700, 'key': 80400804}`
So the conversion is right 👍, but in fgliar app `17.0 C`is shown.

**Comment by chiefcomm** [comment]
Thanks at least it confirms that everything is converting OK - as the API is undocumented and has been reverse engineered this is the only viable option.

The API gives 3 temperature I could extract only one made sense as the current temperature, looking at other reverse engineered plugins all are using the display_temperature.  Most likely this isn't the same sensor the the Mobile App is using (it is impossible to tell as the API is all we have) - the question, is this a big deal and can people live with this or do we turn it into an option to display (or not).

adjust_temperature an input
display_temperature an output
outdoor_temperature an output (in my case none reported)

At this minute with my A/C turned off the Mobile App is saying 28.0°C and HA is displaying 24.3°C, for sure 28.0°C is nearer the real temp in Sydney today :-)

**Comment by bigmoby** [comment]
Hi @chiefcomm and thanks again for your contributions! 🙌
All my "envy" of Sydney's current temperatures aside, here in Sicily (Italy) is winter and too cold for me! 😜 Please could you give me feedback about this "daily" release?
https://github.com/bigmoby/fglair_for_homeassistant/compare/v0.1.6...v0.1.7

**Comment by chiefcomm** [comment]
Hi @bigmoby oh nice I never managed to get to Sicily in my travels, I'll add it to my list of places to visit.
Latest release is one way to handle it and gives more flexibility so yes lets go with that and see if it solves for people.   I may have mentioned earlier in that I think this is either a completely different sensor in the unit, for me the variance has been so minor I never bothered to worry about it (I never look at the mobile app).

**Comment by Yakie996** [comment]
Hi, sorry I dit not had the time last couple of days, thanks for update!

**Comment by chiefcomm** [comment]
Looks good @bigmoby, stuck indoors today it's a bit warm outside (about 31°C) so sitting inside with A/C on and testing the new release out.   As I said earlier I have very marginal differences between the App 23.0°C vs HA 22.8°C but the offset does appear to work in test were I added a +0.2°C offset :-)

![image](https://user-images.githubusercontent.com/45157523/212520349-8c65be5c-81eb-4136-ad77-2955b8efa91f.png)

![image](https://user-images.githubusercontent.com/45157523/212520260-fb4a7e1d-9906-47f6-aed4-735296ac0844.png)

![image](https://user-images.githubusercontent.com/45157523/212520242-aaecf90c-5cae-4da6-9c22-ca7c3878a86b.png)

**Comment by bigmoby** [comment]
> Hi @bigmoby oh nice I never managed to get to Sicily in my travels, I'll add it to my list of places to visit. 
Sicily is a wonderful place! You're welcome! 🙌 ...but in summer it's better! 😅
Oook, so I suppose we could close this issue 🚀
