### ISSUE TITLE
Current Temp in 'us' region is not properly converted

### ISSUE THREAD

**Issue by mtbBrian** [bigmoby/fglair_for_homeassistant#16]
I am in the US and prefer temperature in Fahrenheit. It appears that the integration is converting the value passed (degF) as if it is Celsius into Fahrenheit. Current attributes below. Additionally, the "unconverted" value is a little off from app same as other issue points out.

![ac_attributes](https://user-images.githubusercontent.com/96792004/211804310-14f39352-6492-4ffc-9610-51dc4ec339c8.PNG)

**Comment by chiefcomm** [comment]
@mtbBrian weird would you share your config file or confirm region is set to 'us' as below.

````
climate:
  - platform: fglair_heatpump_controller
    username: !secret FGLAIR_USER
    password: !secret FGLAIR_PASS
    region: 'us'

**Comment by mtbBrian** [comment]
Configuration copied from configuration.yml
```
climate:
  - platform: fglair_heatpump_controller
    username: !secret FGLAIR_USER
    password: !secret FGLAIR_PASS
    region: 'us'
    tokenpath: '/config/token.txt'
```

Thank you for reviewing.

**Comment by chiefcomm** [comment]
Thanks @mtbBrian although this confuses me more :-(

We'll have to add some debugging code as there seems some idiosyncrasies that come from some units causing differences.   I just switched my config to 'us' and immediately I have temp displayed exactly as the value from the API in Fahrenheit with 'us' in the config.

@bigmoby I'll create a pull request to add additional debugging to see if we can sort this out, this may also help troubleshoot differences in the FGLAir app vs HA.

````
climate:
  - platform: fglair_heatpump_controller
    username: !secret fglair_username
    password: !secret fglair_password
    region: 'us'
    tokenpath: 'token.txt'
````
![image](https://user-images.githubusercontent.com/45157523/211954270-f4762a85-7184-4cbd-a7fb-464cac6211e2.png)

**Comment by bigmoby** [comment]
Yes please, thank you 🙏

**Comment by chiefcomm** [comment]
> Yes please, thank you 🙏

Done pull request created - please create a beta release so we can test what the API is returning.

**Comment by chiefcomm** [comment]
@mtbBrian please install version v0.1.4 and add the following to configuration.yaml.
````
logger:
  default: critical
  logs:
    custom_components.fglair_heatpump_controller.climate: debug
    homeassistant.components.climate: debug
````

I'm really interested in the lines below from your logs.

2023-01-13 07:39:14.484 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature json: {'value': 7500, 'key': 93872419}
2023-01-13 07:39:14.484 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature: 7500
2023-01-13 07:39:14.484 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Region: au

**Comment by mtbBrian** [comment]
Ok. Updated to v0.1.4. Logs below
```
2023-01-12 16:46:53.929 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate hvac_mode: 6
2023-01-12 16:46:53.929 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature json: {'value': 7000, 'key': 239566734}
2023-01-12 16:46:53.930 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Display_temperature: 7000
2023-01-12 16:46:53.930 DEBUG (MainThread) [custom_components.fglair_heatpump_controller.climate] Region: us
```
![image](https://user-images.githubusercontent.com/96792004/212189088-37e90d1d-3f9c-42ec-99f8-b1c45106b6f5.png)

**Comment by mtbBrian** [comment]
Seems like current_temperature is always in F*100 regardless of region.

I will also note that the logs were copied after I manually polled the current temp from the app as that seems to then update HA through your integration. It seems to always be 2degF warmer according to HA compared with app.

Thanks again for addressing this.

**Comment by chiefcomm** [comment]
@mtbBrian you are correct the API reports current temp in F*100.  Right now I'm very confused as something weird is going on.   In your case the data extracted from the FGLAir API is 7000 (70F) yet somehow HA is displaying 158.

The code is doing 1 of 2 things either leaving as F if region is 'us' or converting to C therefore I would understand if you were seeing either 70F or 21C but 158 makes no sense at all.   We now move way past my coding skills @bigmoby @m4thieulavoie any ideas?

The other question is anyone else experiencing this?

````
        if self._region == 'us':
           return round(curtemp['value'] / 100, 1)
        else:
           return round((curtemp['value'] / 100 - 32) * 5/9, 1)

**Comment by chiefcomm** [comment]
Another clue 70C is 158F so now I wonder if there is something in HA assuming this is in C and converting to F

**Comment by mtbBrian** [comment]
Interesting. The code from climate.py does look indicate that 70f should be passed to HA. Maybe this is converted on the HA side or somewhere else in the integration. I wish the logger passed TEMP_CELSIUS. It is also curious MIN_TEMP and MAX_TEMP are set in degC but show in HA as degF

**Comment by chiefcomm** [comment]
@mtbBrian yes one word is interesting....   Try this and lets see what happens I've a strange feeling that 21.1°C (70°F) will pass to HA and miraculously 70°F will appear in HA.

edit your config to the below which will convert the temp to Celsius and maybe HA will convert it back - my theory is there is some conversion happening in HA.   How to trace what the integration is providing to HA is the big question :

````
climate:
  - platform: fglair_heatpump_controller
    username: !secret fglair_username
    password: !secret fglair_password
    region: 'test'
    tokenpath: '/config/token.txt'

**Comment by chiefcomm** [comment]
@mtbBrian my theory above is looking ever likely as I read the developer docs https://developers.home-assistant.io/docs/core/entity/climate/ as the temp is defined in Celsius elsewhere in the code :-)

I'm going to see if I have enough bits and bobs to build a development HA instance and test my theory by setting the region as US with US units.  In the mean time let me know what happens if you change the config as suggested above.

**Comment by chiefcomm** [comment]
@mtbBrian issue solved after building a test platform (I was thinking about having a test bed anyway thanks for the push)

The integration sets the units as Celsius and as we are converting to Fahrenheit for the US therefore when HA receives the temp which it believes is a temp in °C HA then converts the temp to Fahrenheit hence why you see a crazy high temperature.

This is useful as we no longer have to worry about units :-) 

Therefore we'll have to make a code change @bigmoby - I'll create a pull request and have this done ASAP.

My config for testing:
````
climate:
  - platform: fglair_heatpump_controller
    username: !secret fglair_username
    password: !secret fglair_password
    region: 'us'
    tokenpath: 'token.txt'
````
![image](https://user-images.githubusercontent.com/45157523/212280158-f33e7f60-97d6-4f0e-839e-8cd2cffcea52.png)

**Comment by bigmoby** [comment]
Well done @chiefcomm 🚀
Thank you 👍

**Comment by chiefcomm** [comment]
@mtbBrian v0.1.5 is released which should address this issue for the US.

**Comment by mtbBrian** [comment]
Well done. Working as expected now.  Thanks to @bigmoby and @chiefcomm  for working this through!
