### ISSUE TITLE
Support ASU9RLS

### ISSUE THREAD

**Issue by chheiss** [bigmoby/fglair_for_homeassistant#169]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The ASU9RLS3Y is reported by the integration as not supported. I am using the FGLAir app without problems for years now.

### Describe the solution you'd like

Support above AC

### Describe alternatives you've considered

None

### Additional context

None

**Comment by bigmoby** [comment]
> The ASU9RLS3Y is reported by the integration as not supported.

Hi @chheiss I'm sorry probably I miss something but where's reported that is not supported? Have you some integration's issue?

**Comment by chheiss** [comment]
It says: This device is not supported by FujitsuHVAC.

**Comment by bigmoby** [comment]
Sorry, is it in this integration reported?

**Comment by bigmoby** [comment]
@chheiss I suppose you're referring to this issue: https://github.com/home-assistant/core/issues/125379
In HA 2024.9.0 there's a new integration support for FGLair device. I'm not the maintainer for that HA official integration, you should ask to @crevetor (https://github.com/crevetor).
