### ISSUE TITLE
Invalid or missing 'value' in get_af_vertical_num_dir response

### ISSUE THREAD

**Issue by skydado** [bigmoby/fglair_for_homeassistant#175]
## System Information

version | core-2024.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1409
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 439.4 GB
disk_used | 16.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), File editor (5.8.0), Duck DNS (1.18.0), NGINX Home Assistant SSL proxy (3.10.1), Home Assistant Google Drive Backup (0.112.1), GoSungrow (3.0.7), Mosquitto broker (6.4.1), Network UPS Tools (0.13.1), Firefox (1.2.0), Whatsapp (1.3.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 19
views | 27
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 9, 2024 at 16:44
-- | --
current_recorder_run | September 18, 2024 at 14:25
estimated_db_size | 1056.97 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.20
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

System Logs full of this ERROR messages:
Invalid or missing 'value' in get_af_vertical_num_dir response: {'value': 0, 'key': 142922390}
Invalid or missing 'value' in get_af_vertical_num_dir response: {'value': 0, 'key': 142919124}

It seems they are not impacting basic functionalities.

This is my Fujitsu clima: ARXG24KMLA

### Reproduction steps

errors in logs

### Debug logs

```text
This error originated from a custom integration.

Logger: pyfujitsugeneral.splitAC
Source: custom_components/fglair_heatpump_controller/climate.py:534
integration: FGLair heat pump controller integration (documentation, issues)
First occurred: 14:26:00 (1361 occurrences)
Last logged: 18:13:04

Invalid or missing 'value' in get_af_vertical_num_dir response: {'value': 0, 'key': 142922390}
Invalid or missing 'value' in get_af_vertical_num_dir response: {'value': 0, 'key': 142919124}
```

**Comment by bigmoby** [comment]
Hi @skydado ,
please if you want to try with: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.3.22

**Comment by skydado** [comment]
Hi @bigmoby, unfortunately it does the same:

![image](https://github.com/user-attachments/assets/b776320c-adde-453a-a4f0-2ead3546ef99)

![image](https://github.com/user-attachments/assets/fd8eba3b-ccc7-4e71-aa5e-e05d514c8856)

**Comment by Dev-Fabry** [comment]
Hi, same problem for me but with Horizontal (get_af_horizontal_num_dir response)

core-2024.9.3 and integration v0.3.22

**Comment by bigmoby** [comment]
Hi guys,
please have a check with this release: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.3.23
