### ISSUE TITLE
Unable to use in automations due to lack of device enlisting

### ISSUE THREAD

**Issue by maxplanckk** [bigmoby/fglair_for_homeassistant#178]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The AC is being listed as an entity only but not as a device. Though I am able to manually control all the aspects of the AC through the dashboard, I am not able to do any automations. 

### Describe the solution you'd like

List the device and and enlist all the actions separately from the entity.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by SgtFlippy** [comment]
You can call them in automations with climate.room
