### ISSUE TITLE
Floor mounted Fujitsu AGU12RLF showing unavailable

### ISSUE THREAD

**Issue by cmchauvin** [bigmoby/fglair_for_homeassistant#19]
In release 0.1.0 this unit functions perfectly. Every release since then (starting with release 0.1.1) the unit shows as unavailable and refused to connect to Home Assistant. 

https://user-images.githubusercontent.com/17072686/212418877-9fd836b0-98e8-44f5-9540-84c4733f9f67.png

**Comment by bigmoby** [comment]
Hi @cmchauvin have you tried to delete token file and restart HA?

**Comment by bigmoby** [comment]
Closed stale issue. Please reopen if needed.
