### ISSUE TITLE
Indvidual Units Not Responding

### ISSUE THREAD

**Issue by leacho73** [bigmoby/fglair_for_homeassistant#20]
Hi,

I have noticed that a particular unit, connected to the same FGLair account does not respond when sent commands from HA via this integration - previously I assumed it was a token issue, but doing some more research, it does look like its related to a individual unit. For example, I have 2 units, which work absolutely fine via the FGLair app - however, if I try to turn this particular unit on to 'Auto' from home assistant - it doesn't respond.

If I turn the unit on via the FGLair app - I am able to see the unit update in Home Assistant - and from that point I can control the unit - including turning it off - however, I just can't turn it on. If I reboot home assistant, I can control that particular unit again for a short time before it stops responding to hvac_mode:auto again.

The second unit works flawlessly every time using this integration - so not sure what is going on.

Nothing in the logs to say what is going on either - let me know if there is anything I can do to help troubleshoot.

Thanks
Leacho

**Comment by bigmoby** [comment]
Hi @leacho73 thank you for reporting that. It's hard to investigate remotely so I could have conjectures only...could it be an issue caused by the interaction between the official FGLair mobile app and the integration?!
