### ISSUE TITLE
Missing 'Fan Mode' - "Quiet" or "Diffuse"

### ISSUE THREAD

**Issue by Adunite85** [bigmoby/fglair_for_homeassistant#201]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Dear Contributors,
Thank you for making this integration an official one!

Current implementation only offers fan modes of "Low", "Medium", "High" and "Auto", but missing one setting that's slower than "Low" that is available in the official app named as "Quiet", and in the previous community made integration as "Diffuse"
![Screenshot_20241112_174050_FGLair](https://github.com/user-attachments/assets/d8c0ba70-4a1f-49e9-a63b-527be969d5cf)

When set through the app, it shows up as blank on the card, and as an exception if the function is being called via a script.
![image](https://github.com/user-attachments/assets/1c5390a7-7b40-405b-93d3-d98d290a7648)

### Describe the solution you'd like

Please consider reviewing the code to include this setting.
Controller is an AP-WF2E module embedded in a ASYG12KPCA.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by bigmoby** [comment]
> Thank you for making this integration an official one!

Hi @Adunite85 
This is not the official Fglair integration, anyway I'll try to analyze how this feature could be implemented. 👍
Regards, 
Fabio

**Comment by Adunite85** [comment]
Thanks Fabio!
Please let me know if you need any help with testing, or additional information!
BR,
Greg

**Comment by bigmoby** [comment]
Hi @Adunite85 and @fdcastel please could you tell me the version number of the fglair component you have installed?

The quiet or diffuse mode is already implemented for a long time.

```
    def get_fan_speed_desc(self) -> str:
        """Get the description of the fan speed.

        The supported fan speeds vary from device to device. The available modes are
        read from the Device capability attributes.

        """
        FAN_SPEED_DICT = {0: "Quiet", 1: "Low", 2: "Medium", 3: "High", 4: "Auto"}

        fan_speed = self.get_fan_speed()["value"]
        if fan_speed == 5:
            """For very few AC the resulting value is 5 BUT this value "5" is a not documented value,
            I assume it as the Low value according:
            https://github.com/deiger/AirCon/blob/master/devicetypes/deiger/hisense-air-conditioner.src/hisense-air-conditioner.groovy#L198
            """
            return FAN_SPEED_DICT[1]

        if fan_speed == 7:
            """For very few AC the resulting value is 7 BUT this value "7" is a not documented value,
            I assume it as the High value according:
            https://github.com/deiger/AirCon/blob/master/devicetypes/deiger/hisense-air-conditioner.src/hisense-air-conditioner.groovy#L204
            """
            return FAN_SPEED_DICT[3]

        if fan_speed == 9:
            """For very few AC the resulting value is 9 BUT this value "9" is a not documented value,
            I assume it as the Auto value according:
            https://github.com/deiger/AirCon/blob/master/devicetypes/deiger/hisense-air-conditioner.src/hisense-air-conditioner.groovy#L210
            """
            return FAN_SPEED_DICT[4]

        return FAN_SPEED_DICT[fan_speed]
```

**Comment by bigmoby** [comment]
Oooops 😅
I have a "very slight suspicion" that you are using the official home assistant integration! this is my custom integration! ...which I think works much better than the official one, but this is just my humble opinion! 😉

**Comment by Adunite85** [comment]
Sorry, and thank you!
We both got it confused; I was following a link from under a discussion on the community forums about the "official" integration.
It works like a charm, and has all features I was missing.
![image](https://github.com/user-attachments/assets/c0c9f172-c77a-4767-80bb-8032eb91e1bc)
I wonder if there's a way or possibility to make your integration more visible.

**Comment by bigmoby** [comment]
No problem at all, @fdcastel @Adunite85 ! 🙌
Please star this project if it's useful for you ⭐️
