### ISSUE TITLE
card dont show aux heat button

### ISSUE THREAD

**Issue by mrpatate76** [bigmoby/fglair_for_homeassistant#21]
Hello, 
i amange to get everything working, but in you example, i see a aux heat button, but it dont show up in my card. Sorry if it is my fault, i am new to HA. this is what i got so far:
![image](https://user-images.githubusercontent.com/48101511/213781493-cac50f9a-064c-4871-92a4-65043ebf48ea.png)

**Comment by chiefcomm** [comment]
@mrpatate76 this feature is not currently implemented as per the readme documents.

@bigmoby we could possibly implement this via the presets "BOOST" option however it would require some coding effort to which my coding skills are lacking to relate "BOOST" to FGLair "powerful_mode".

**Comment by chiefcomm** [comment]
@bigmoby well I shocked myself I managed to implement FGLair Powerful Mode via the Boost setting.  As FGLair seems not to support aux_heat I propose to implement via preset=boost.   I'll create a PR and it would be great if you and others could test as it works great for me :smiley:

**Comment by chiefcomm** [comment]
@mrpatate76 this is implemented in v0.1.8 via the preset dropdown.  @bigmoby I think this issue can be closed.

![image](https://user-images.githubusercontent.com/45157523/213951094-7d4e5ee3-5716-4a97-9fd7-72dd74183314.png)

**Comment by bigmoby** [comment]
Yes thank you @chiefcomm 🚀
