### ISSUE TITLE
Integration not loaded after update

### ISSUE THREAD

**Issue by JSamsom72** [bigmoby/fglair_for_homeassistant#215]
### System Health details

Core: 2024.12.0
Supervisor: 2024.11.4
Operating System 14.0
Frontend: 20241127.4
FGLair: 0.3.25

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After the update to above releases, the FGLair heat pump controller integration is not loaded anymore.

### Reproduction steps

1. Install Core
2.
3.
...

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by SrBurner** [comment]
Same here!

**Comment by SrBurner** [comment]
I have tried to remove and reconfigure it. But now I can’t configure it again:
Couldn’t load configuration workflow: 500 Internal Server Error Server got itself in trouble

**Comment by Niek** [comment]
Same issue, seems related to the Python upgrade.

**Comment by mrpatate76** [comment]
same for me, upgraded python, but aiofiles, updated to 23.1.0-1 and requirements are for 23.2.1

**Comment by Niek** [comment]
The requirements.txt is updated now, but this still needs changing @bigmoby:
https://github.com/bigmoby/fglair_for_homeassistant/blob/a842d8de25050c35400a0d66563b53eebdc05d2a/custom_components/fglair_heatpump_controller/manifest.json#L18

Thanks for your work on this!

**Comment by bigmoby** [comment]
Has been released https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.3.26 that solves.
