### ISSUE TITLE
After Upgrade of HA 2024.12.0 fglair does not run any more

### ISSUE THREAD

**Issue by stefferber** [bigmoby/fglair_for_homeassistant#218]
## System Information

version | core-2024.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.51-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1479
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 8.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.2), Advanced SSH & Web Terminal (19.0.0), RaspberryMatic CCU (3.79.6.20241122), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17. November 2024 um 15:48
-- | --
current_recorder_run | 6. Dezember 2024 um 19:34
estimated_db_size | 87.25 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Custom integration "fglair_heatpump_controller" does not start after upgrading to HA 2024.12.0

### Reproduction steps

1. Restart HA
2. View log files

### Debug logs

```text
Logger: homeassistant.util.package
Quelle: util/package.py:152
Erstmals aufgetreten: 6. Dezember 2024 um 19:34:23 (3 Vorkommnisse)
Zuletzt protokolliert: 6. Dezember 2024 um 19:34:25

Unable to install package aiofiles==23.2.1: × No solution found when resolving dependencies: ╰─▶ Because you require aiofiles==23.2.1 and aiofiles>=24.1.0, we can conclude that your requirements are unsatisfiable.

Logger: homeassistant.setup
Quelle: setup.py:269
Erstmals aufgetreten: 6. Dezember 2024 um 19:34:25 (1 Vorkommnisse)
Zuletzt protokolliert: 6. Dezember 2024 um 19:34:25

Setup failed for custom integration 'fglair_heatpump_controller': Requirements for fglair_heatpump_controller not found: ['aiofiles==23.2.1'].
```

**Comment by stefferber** [comment]
Did upgrade to HA 2024.12.1 but still same problem

## System Information

version | core-2024.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.51-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1479
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 8.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.2), Advanced SSH & Web Terminal (19.0.0), RaspberryMatic CCU (3.79.6.20241122), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17. November 2024 um 15:48
-- | --
current_recorder_run | 7. Dezember 2024 um 12:17
estimated_db_size | 87.25 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by Naguz** [comment]
Can confirm. I am assuming this is because HAOS or HA now comes with 24.1.0. Assuming no breaking changes in aiofiles, I assume a simple change in the requirements is all that's needed, I am willing to helot test this if possible.

**Comment by axelsegers** [comment]
Thank you. when will this be released?

**Comment by bigmoby** [comment]
Hi guys, it has been solved some days ago with: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.3.26

**Comment by axelsegers** [comment]
How do i get this latest version in HA?  Everything up-to-date and still using v0.3.25

**Comment by axelsegers** [comment]
Yes but for some reason it didn't show the new version. I forced the update manually and it works now. 
Thanks

**Comment by stefferber** [comment]
Thx for fixing so quickly. I can confirm that it is up-and-running with V0.3.26 again.
