### ISSUE TITLE
Tokenpath not applying as "optional"

### ISSUE THREAD

**Issue by chiefcomm** [bigmoby/fglair_for_homeassistant#30]
Tokenpath is specified as optional, however appears to be mandatory as conf fails if not specified.  @bigmoby I had a look and did not see where this is failing in the API, I am not 100% clear on why this is not working as an optional field which it should be :-(

2 options as I see it :-

1. Change the readme to reflect as mandatory
2. Identify the issue with pyfujitseu api.py (if that is where the issue lies)

Thoughts?

**Comment by bigmoby** [comment]
Hi @chiefcomm , ok...the first solution, ok?! 😅

**Comment by bigmoby** [comment]
Fixed with https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.0
