### ISSUE TITLE
fglair_for_homeassistant: is not a valid add-on repository

### ISSUE THREAD

**Issue by LilianGzt** [bigmoby/fglair_for_homeassistant#35]
Hi, 

I am having a hard time to integrate fglair_for_homeassistant. When I try to add the repository (Add-on->Store->Repository) I get this error:

https://github.com/bigmoby/fglair_for_homeassistant 
is not a valid add-on repository

![Capture d’écran 2023-03-10 075007](https://user-images.githubusercontent.com/91667508/224244201-a882e6d5-4014-4d85-8ae5-85a7205a99f7.png)

What I'm doing wrong here ? (I'm new to HomeAssistant)

Here some info on my HA setup:
Home Assistant 2023.3.3
Supervisor 2023.03.1
Operating System 9.5

Frontend 20230309.0 - latest

Best regards,

**Comment by chiefcomm** [comment]
fglair_for_homeassistant like many add-ons is not an add-on it is a HACS repository, you would need to install HACS first prior to installing this HACS add-on.

Read up on HACS here https://hacs.xyz/

Otherwise you can follow the manual setup process.

**Comment by bigmoby** [comment]
Hi @LilianGzt as suggested by @chiefcomm it's not an add-on, it's an external integration installed by HACS or manually, as you prefer. Please read carefully the documentation at: https://github.com/bigmoby/fglair_for_homeassistant#hacs

**Comment by LilianGzt** [comment]
Hi,
Thank you. Everything is working now !
