### ISSUE TITLE
Heat mode availability toggling with HA restarts

### ISSUE THREAD

**Issue by logicland** [bigmoby/fglair_for_homeassistant#36]
First, thank you so much for this amazing and ever improving integration, it's truly very much appreciated.

The integrations been running rock solid for 6 months, with one tiny issue, with each HA restart the Operation "Heat" toggles between being available or unavailable, also repeatable. All other functions work, but as I only ever use HEAT along with Boost when necessary, sometime I get plunged into the cold.

It's not a big issue as HEAT can be restored by just restarting HA it and it will stay functional until then next restart occurs.

It's as if there's an uninitialized status or bit that gets toggled with each restart.

Before posting and to confirm, i just  deleted and reinstalled FGLair and repeated the issue.

Note its is running on HA 2023.3.3 and the Fujitsu Air Conditioner Model is ASYG09KGTE, about 6 months old.

configuration.yaml
climate:
  - platform: fglair_heatpump_controller
    username: xxxxxxxxxx@yyy.zzz
    password: xxxxxxx
    region: "eu"
    tokenpath: "token.txt"
    temperature_offset: -2.0

I'll be happy to help where I can.

**Comment by mtbBrian** [comment]
@andhya I recommend opening a separate issue as I believe this is different than @logicland 's OP.

I actually have the same the same issue and have been working around it. However, I do really wish this worked. You have explained the problem well and exactly as I experience it. FYI my model is ASU12RLS3Y

**Comment by bigmoby** [comment]
Hi guys, I'm sorry but I'm not able to reproduce it please give me the steps I've to follow. Is it the right procedure to reproduce it?
- the ac is off
- switch to heat it
- the ac turns on in heat mode
- restart HA
- then the ac is on but in cool mode
Is it right!?

**Comment by andhya** [comment]
For me, the steps are;
- ac is off (or on, but in cold/auto etc)
- select 'heat' mode in ha
- ac remains off (or in cold/auto etc)
- ha reverts to showing mode as 'off' (or cold/auto etc) after a second or so

My understanding is that this behaviour occurs for OP @logicland on every other boot? It occurs for me all the time, and I think for @mtbBrian too?

At some point when I have some time, maybe this weekend, I'll see if I can work out how to make that API call in a way that I can capture the response... But if anyone works out a good test procedure before then I'll run that!

**Comment by mtbBrian** [comment]
The steps described by @andhya are the same behavior I am experiencing. I have not found a sequence of setting changes or service calls which will allow 'heat' mode to stick through HA

**Comment by logicland** [comment]
**Update**
The "no Heat" issue only occurs if Heat was "On" at restart (and only Heat) which explains the apparent "toggling" effect on successive restarts.

**Once in error**
- Heat can be turned Off but never back On again, however all other Operations, Presets & Modes function normally.
- Heat can be selected remotely and turned Off by HA but again not back On

If Heat is Off at restart the A/C runs normally.

**Comment by bigmoby** [comment]
Ok thank you guys! Are only the versions 2.x.x affected by this bug or either the versions 1.9.x too?

**Comment by mtbBrian** [comment]
Same behavior with 1.9.x and 2.0.x

**Comment by bigmoby** [comment]
> Same behavior with 1.9.x and 2.0.x

Ok thanks 👍

**Comment by bigmoby** [comment]
Hi guys, I've tried to fix this bug but I wasn't able to reproduce it in my current HA environment so...I've coded it in "blindness" mode. I hope it can solve your installation too.
Enjoy: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.6
