### ISSUE TITLE
Changing temp on non-Celcius scale (primarily US Fahrenheit users)

### ISSUE THREAD

**Issue by Rydcal** [bigmoby/fglair_for_homeassistant#37]
Disclaimer- This is probably more of an enhancement request, as nothing new is broken.  

Those who try to change temp on the "US- Fahrenheit" HA thermostat have probably noticed that it only works on certain values that happen to convert into allowed Celcius temps.  I've largely solved the issue by using specific tested values in automations and leaving the HA thermostat dial alone in the interface.  For example if you want 71 degrees you can set 'temperature: '70.7' in an automation (or in the climate.set_temperature service) and it will work since that neatly converts to 21.5 C.  

I haven't been able to figure out where in the integration to do this, but I've been testing some python that will take any F value and deliver the nearest .5 degree Celcius.  I'm pretty sure this is the missing magic.

```
 def fahrenheit_to_half_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5 / 9
    half_celsius = round(celsius * 2) / 2
    return half_celsius 
```

So calling it for something like 69F gives:

```
> fahrenheit_to_half_celsius(69)
20.5
```

If anybody has ideas of where to insert this in the code, I'd love to try it.  It would probably need to operate before self.adjust_temperature, but not sure how best to translate/intercept incoming temp changes.

**Comment by bigmoby** [comment]
Hi @Rydcal thank you so much for your analysis 🙌I'll provide to fix it asap

**Comment by bigmoby** [comment]
Hi @Rydcal ,
I'm a "celsius" user but I think it's almost the same issue. I've tested with:

```
service: climate.set_temperature
data:
  temperature: 22.6
target:
  entity_id: climate.[xyz_entity]
```

Please try this release: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.7
I hope it could solve your request 👍

**Comment by Rydcal** [comment]
Perfection!

**Comment by Rydcal** [comment]
Actually, I may have spoken too soon.  I am seeing "--" on the FGlair app when changing temperature via the HA integration and then it resets to the previous temperature.  It does still work if you use a number like "68" which translates to 20 C.  Not sure what's up, we may be getting closer.

**Comment by bigmoby** [comment]
Hi @Rydcal please post here the example of the service invoked with the payload you're sending. Otherwise I'm not able to help you.

**Comment by Rydcal** [comment]
Using Services tab:

service: climate.set_temperature
data:
  temperature: 67
target:
  entity_id: climate.ac_uty_***********

After about 10 seconds of showing "temperature: 67"  it reverts back to show 68 in the states table:

hvac_modes: heat, cool, auto, dry, fan_only, off
min_temp: 61
max_temp: 86
target_temp_step: 1
fan_modes: auto, low, medium, high, diffuse
preset_modes: none, eco, boost
swing_modes: off, on, vertical, horizontal
current_temperature: 69
temperature: 68
fan_mode: auto
preset_mode: none
swing_mode: off
friendly_name: *****
supported_features: 57

I don't see any errors in the Log, and no new entries in Logbook.  

My existing automations, which use the same service but with special Celcius compatible values like "70.7" appear to reliably set the temperature.

**Comment by chiefcomm** [comment]
Hello @Rydcal in an attempt to replicate this issue I have set my test system to Fahrenheit and I am unable to repeat your experience, my account is in the US so we should be comparing apples with apples.

Set temp to 70°F
Switch on / auto
Change temp to 67°F

5mins later everything remains at 67°F

hvac_modes: off, heat, cool, auto, dry, fan_only
min_temp: 61
max_temp: 86
target_temp_step: 1
fan_modes: auto, low, medium, high, diffuse
preset_modes: none, eco, boost
swing_modes: off, on, vertical, horizontal
current_temperature: 73
temperature: 67
fan_mode: auto
preset_mode: none
swing_mode: off
friendly_name: *****
supported_features: 57

**Comment by Rydcal** [comment]
chiefcomm- What version of HA are you running? 

I'm running HAOS on a VM:

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

After rotating the temp dial to 66, it stays for 28 seconds and then resets to 68.

**Comment by chiefcomm** [comment]
@Rydcal my test system is running on Pi3 (rpi3-64)

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

I could not replicate the issue you experience which makes it very hard to troubleshoot - I set (and forget) at 66.  Screenshots captured 5mins after setting the temp.

![image](https://user-images.githubusercontent.com/45157523/228384018-537a5f9c-316f-4f20-ae75-896d849eafa8.png)
![Screenshot_20230329-094434](https://user-images.githubusercontent.com/45157523/228383933-03d71c3c-081d-4922-8119-79585c692750.png)

**Comment by Rydcal** [comment]
I think this is all set.   HACS had a pending update which I had not previously noticed, after applying 0.2.7 and bouncing we're good.  I'm seeing the .5 steps and temp changes seem to stick.  Thanks all!
