### ISSUE TITLE
Heat mode not selectable

### ISSUE THREAD

**Issue by andhya** [bigmoby/fglair_for_homeassistant#39]
I'm trying to operate an ASYG12KMCC unit using a UTY-TFSXW1 WiFi adaptor from homeassistant on HA Yellow. I can adjust temperatures and presets fine, and can change mode from Heat to Off successfully, but am unable to change mode to Heat from any other mode (critically, from 'Off' 😅 ).

Auto, Cool etc can be selected from HA, but not Heat; the mode just reverts to whatever was previous.

Heat can be selected from the FGLAir app and this gets updated in HA.

I've tried restarting HA and haven't been able to replicate the alternating success of #https://github.com/bigmoby/fglair_for_homeassistant/issues/36
so opened this as a new issue on advice of @mtbBrian who has a similar issue with their ASU12RLS3Y

Thanks again for this project though - even before getting to the potential for automations, apart from this issue it's so much more responsive than the FGLAir app!

**Comment by bigmoby** [comment]
Hi @andhya I refactored the code in the operation mode function, please try this: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.6
Give me a feedback if it solve, please

**Comment by andhya** [comment]
Just updated and operated remotely - it sticks in the UI and matches and follows the FGLAir app, so looks very promising, thanks @bigmoby ! 

Just need double check that the unit operates as expected when I get home, but given it's agreeing with the FGLAir app it seems very likely.

**Comment by mtbBrian** [comment]
This update seems to be working for me as well. I tested turning unit from 'heat' to non heat modes ('off' and 'fan only'). This worked properly as in prior versions. The real test is going back to 'heat'. It worked! I will see if all other functions work properly, but all appears good. Thanks @bigmoby!

**Comment by andhya** [comment]
All working, have sent you some beers @bigmoby thanks!

**Comment by bigmoby** [comment]
Thank you so much @andhya 🙏I really appreciate!
