### ISSUE TITLE
Multiple accounts 

### ISSUE THREAD

**Issue by SvenBuis** [bigmoby/fglair_for_homeassistant#41]
Hello,

Not sure where else to ask this, but is it possible to use this integration with multiple FGLair accounts?

If not, is this something that could be implemented?
If yes; how does the integration handle duplicate entity names?

Regards,
Sven

**Comment by bigmoby** [comment]
Hi @SvenBuis,
please take a look at the documentation (https://github.com/bigmoby/fglair_for_homeassistant#usage). No, it's not possible.
Regards,
Fabio

**Comment by SvenBuis** [comment]
With the new integration method I see the option to "add entry".

Because I don't have the ability to just test it I'll ask first before I'll try:
- Does it now support multiple accounts?
- If yes; how does is handle the same names on multiple accounts (2x 'living room' for example).

**Comment by bigmoby** [comment]
Hi @SvenBuis ,
yes with this new versione you should be able to define two different accounts (with two different username!).
You should, but unfortunately I haven't tested it, I've one account only.
Please, give me your feedback 🙏

**Comment by SvenBuis** [comment]
hi,

I will test it this week.

One other questions (if I may). For does the temperature_offset do. I
couldn't find it anywhere in the FGLair docs, even tried to find in in the
API docs.

Op do 26 okt 2023 om 12:05 schreef BigMoby ***@***.***>:

**Comment by bigmoby** [comment]
Ok @SvenBuis , I implemented `temperature_offset` in order to normalize the displayed temperature with the current real temperature.

**Comment by SvenBuis** [comment]
Hi,

I have tested it. The integration doesn't handle the duplicate entities, so
it only import the non-duplicates (understandable).

[image: image.png]

So 2 accounts works, but you'll need to watch how you call the units.

Op do 26 okt 2023 om 13:05 schreef BigMoby ***@***.***>:
