### ISSUE TITLE
FGLAIR vs AIRSTAGE

### ISSUE THREAD

**Issue by dpudia** [bigmoby/fglair_for_homeassistant#42]
Hi,
It's possible to integrate commands for airtstage. It is the same app of FGLAIR provided by Fujitsu to control air conditioners with external wifi interface.
This is the link of the app:
https://www.fujitsu-general.com/us/airstage-mobile/index.html

**Comment by bigmoby** [comment]
Hi @dpudia, unfortunately, I don't know how could Airstage acts and what kind of functionalities implements.
I read this FAQ:
https://www.fujitsugeneral.com/us/support/faq/airstage-mobile/0125.html
and it sounds to me like impossible to integrate into FGLAIR integration.
I'm sorry,
Fabio
