### ISSUE TITLE
Repository Invalid

### ISSUE THREAD

**Issue by ronsegal** [bigmoby/fglair_for_homeassistant#43]
In latest home assistant for RPi4 (as of 23rd May 2023):
https://github.com/bigmoby/fglair_for_homeassistant is not a valid repository
The same for:
https://github.com/bigmoby/hassio-repository-addon
Other repositories are adding ok.

**Comment by chiefcomm** [comment]
FYI and maybe the key, fglair_for_homeassistant is not an Home Assistant add-on it is a HACS repository. Do you have HACS installed?

**Comment by bigmoby** [comment]
Thanks a lot @chiefcomm 🙌
Hi @ronsegal have you read the installation guide? https://github.com/bigmoby/fglair_for_homeassistant#installation

**Comment by SrBurner** [comment]
I have it installed using HACS no problem
