### ISSUE TITLE
Default Operation mode

### ISSUE THREAD

**Issue by SrBurner** [bigmoby/fglair_for_homeassistant#44]
Hi, is there any way to set "default" operation mode?
When I press on Switch ON using lovelace interface is always turning on as Heat mode and I would like to be in cold mode.
Is there any way.

Is there any work in progress with: Use external temperature sensor as sensor for lovelace?

Thanks a lot

**Comment by vandenbogerd** [comment]
Also interested in this one!

**Comment by SrBurner** [comment]
Right now I use a workaround. I have created an automation: if state changes from off to heat wait a second and change to cool. Hope that helps someone meanwhile.

**Comment by chiefcomm** [comment]
Would you please share the lovelace card you are using as I could not replicate using the "thermostat" card which I use which has only modes Auto, Heat, Cool, Dry, Fan only & Off
![image](https://github.com/bigmoby/fglair_for_homeassistant/assets/45157523/427f94b2-58a9-4790-96f5-bb640fef441c)

**Comment by SrBurner** [comment]
I’m using Mushroom climate card, but is not a lovelace issue, you can replicate it using the service: 
“climate.turn on”. It always turn on in heat mode.

**Comment by chiefcomm** [comment]
Interesting I have never called "climate.turn_on" as I call the service based on the season in conjunction with the temperature of the room @bigmoby any thoughts?

**Comment by bigmoby** [comment]
Hi @chiefcomm , hi guys, honestly unfortunately I have never used that service call either, I usually use the lovelace interface. I'll analyze it.

**Comment by SrBurner** [comment]
I think is used by third integrations like voice assistants

**Comment by bigmoby** [comment]
https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.8
