### ISSUE TITLE
Repository invalid

### ISSUE THREAD

**Issue by akosbalogh** [bigmoby/fglair_for_homeassistant#46]
After trying to add the repository I get an invalid repository error. I added it based on the README:
![image](https://github.com/bigmoby/fglair_for_homeassistant/assets/1980365/61a33206-41a6-4898-bba6-046965edfd8e)

**Comment by akosbalogh** [comment]
I did not try it inside https://hacs.xyz/

**Comment by bigmoby** [comment]
Hi @akosbalogh ,
[fglair_for_homeassistant](https://github.com/bigmoby/fglair_for_homeassistant) is NOT an add-on.
Please read accordingly the README: https://github.com/bigmoby/fglair_for_homeassistant#hacs
