### ISSUE TITLE
FGlair will be replaced by AIRSTAGE

### ISSUE THREAD

**Issue by apf-doit** [bigmoby/fglair_for_homeassistant#47]
Fujitsu recently came out with new WIFI controllers v3. They don't work with FGLair anymore, only the v2 controllers work, the new app now is AIRSTAGE. It seems to be a different platform since the FGLair credentials don't work. Is it possible to adapt the code to AIRSTAGE?

**Comment by bigmoby** [comment]
Hi @apf-doit ,
unfortunately, I don't have devices managed by AIRSTAGE, so I can't help you, this integration is only for FGLair. 
I am sorry,
Fabio

**Comment by Niek** [comment]
You can use this separate repo for Airstage units: https://github.com/danielkaldheim/ha_airstage.git
