### ISSUE TITLE
Repository problem

### ISSUE THREAD

**Issue by Ceccobu** [bigmoby/fglair_for_homeassistant#48]
I'm trying to add the repository to HACS, but it keep display this error:

"https://github.com/bigmoby/fglair_for_homeassistant is not a valid add-on repository"

Is that link correct?

**Comment by chiefcomm** [comment]
@Ceccobu fglair_for_homeassistant is not a Home Assistant add-on it is a HACS repository.

Please setup HACS first following the install for HACS read https://hacs.xyz/ documentation.

Once HACS is installed then install fglair_for_homeassistant

**Comment by Ceccobu** [comment]
Thank you for the explanation, I install HACS and now i can add the repositoy
