### ISSUE TITLE
Current temperature

### ISSUE THREAD

**Issue by claesmathias** [bigmoby/fglair_for_homeassistant#5]
Do you know which API function can be used to retrieve the current temperature? See attached screenshot from FGLair.
![556509D6-F474-4082-81FB-6B9FBA612992](https://user-images.githubusercontent.com/1142852/191001412-d1c0ab23-59c0-4384-827f-d11ae8ae3510.jpeg)

**Comment by chiefcomm** [comment]
I have forked this at https://github.com/chiefcomm/fglair_for_homeassistant which shows the current temperature in °C or °F depending on region (eu, us or cn) @bigmoby have a look and maybe we can bring this into your project.
![image](https://user-images.githubusercontent.com/45157523/209598952-0df51e89-6ad8-4e75-8ab3-a8ea01fad83b.png)

**Comment by bigmoby** [comment]
Great @chiefcomm ! 🚀Do you want contribute opening a PR?

**Comment by chiefcomm** [comment]
Done PR submitted hopeful it works for everyone :-)

**Comment by bigmoby** [comment]
Thanks @chiefcomm 🚀 now, with the v0.1.3 release current temperature will be supported! 👏

**Comment by tricera-eu** [comment]
My temperature in FGLair app is 1.3 degrees Celcius lower than in Home Assistant?

**Comment by chiefcomm** [comment]
> My temperature in FGLair app is 1.3 degrees Celcius lower than in Home Assistant?

The API returns a value in Fahrenheit which is converted to Celsius.  Display_temperature from  json = {**'value': 7300**, 'key': 93872419} then Fahrenheit is converted to Celsius (7300 /100 - 32) * 5/9 = 22.8°C

I cannot offer insight to why the app displays differently although I have noticed minor variance between the API and the FGLair app in my case currently 0.2 °C :-(
