### ISSUE TITLE
option to set airflow direction

### ISSUE THREAD

**Issue by Yakie996** [bigmoby/fglair_for_homeassistant#50]
Hi, 

Is it possible to set the airflow direction, in the app i can set it from 1 to 6 in vertical direction.

![Screenshot_20230910_093910_FGLair](https://github.com/bigmoby/fglair_for_homeassistant/assets/19747119/189f32da-28d2-4e9e-baa2-dda25cd94da4)

**Comment by bigmoby** [comment]
@Yakie996 please try this new version https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.9

**Comment by Yakie996** [comment]
Great it works! thank you 😀
