### ISSUE TITLE
No aux heat

### ISSUE THREAD

**Issue by pbvdven** [bigmoby/fglair_for_homeassistant#6]
Hi, thanks for making an awesome integration for ha. I have a question i don't see aux heat in my  ha not for any of my 4 ac's. Am I doing something wrong? Also i see you mention that we can add an external temp sensor that's really nice is it already possible if so how do i set it up. Thanks again.

**Comment by bigmoby** [comment]
Hi @pbvdven ,
I'm so sorry but it's in the "Known issues and missing features" section and, at the moment, it's a missing feature anche probably it will not implemented in the short period. Feel free to contribute if you want 👍
