### ISSUE TITLE
Entity Not Found

### ISSUE THREAD

**Issue by cmchauvin** [bigmoby/fglair_for_homeassistant#73]
## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.10.0-23-arm64
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4300
Installed Version | 1.33.0
Stage | running
Available Repositories | 1326
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.1
agent_version | 1.1.1
docker_version | 20.10.10
disk_total | 234.5 GB
disk_used | 30.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | AirSonos (3.6.1), File editor (5.6.0), Grafana (9.1.1), InfluxDB (4.8.0), Node-RED (15.0.0), Advanced SSH & Web Terminal (15.1.0), Mosquitto broker (6.3.1), ESPHome (2022.3.1), Studio Code Server (5.13.0), Check Home Assistant configuration (3.11.0), Terminal & SSH (9.7.1), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.111.1), Uptime Kuma (0.9.1), Z-Wave JS (0.2.1), Docker Wyze Bridge (2.3.17)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 21
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 29, 2023 at 1:27 AM
-- | --
current_recorder_run | November 5, 2023 at 2:17 PM
estimated_db_size | 244.02 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I upgrade beyond version 0.2.8 my climate entity shows as unavailable. I have removed all lines from configuration.yaml and have full uninstalled and reinstalled the integration. I have set the configuration fields for the integration entry correctly and the entry is successfully created, but no entities are ever found and my previous entities continue to show as unavailable. 

The only solve is to downgrade to 0.2.8 and re-add the credentials in configuration.yaml

### Reproduction steps

1. Remove all lines from configuration.yaml from previous installations
2. Uninstall FGLair integration from HACS 
3. Delete tokenpath file
4. Restart and ensure custom_components/fglair_heatpump_controller/ folder is gone
5. Re-install FGLair integration via HACS
6. Re-add System Integration and configure with credentials (Same as used in configuration.yaml). Region set to us and using default tokenpath.txt
7. Restart
8. Everything seems okay but no entities are found and previous climate entity continues to show "Unavailable"
9. If I downgrade to 0.2.8, remove the integration from system integrations and add credentials back to configuration.yaml all works okay
...

### Debug logs

```text
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:573
Integration: Climate (documentation, issues)
First occurred: 2:32:20 PM (1 occurrences)
Last logged: 2:32:20 PM

fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 356, in async_update
    await self._fujitsu_device.async_get_display_temperature_degree()
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/splitac.py", line 272, in async_get_display_temperature_degree
    display_temperature_value = self._display_temperature["value"]
                                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'value'
```

**Comment by bigmoby** [comment]
Hi @cmchauvin 
is the version 0.3.3 installed?

**Comment by cmchauvin** [comment]
Yes, 0.3.3 was installed. I’ve confirmed that downgrading back to 0.2.8 and re-adding the lines in configuration.yaml brings everything back online.On Nov 7, 2023, at 12:46 PM, BigMoby ***@***.***> wrote:﻿
Hi @cmchauvin
is the version 0.3.3 installed?

**Comment by bigmoby** [comment]
Hi @cmchauvin 
please could try to execute this steps in order to test together the raised error?
https://github.com/bigmoby/fglair_for_homeassistant/issues/59#issuecomment-1793405888

**Comment by bigmoby** [comment]
Stale issue, no response received. 
Please reopen it if something changes
