### ISSUE TITLE
Units offline

### ISSUE THREAD

**Issue by jarube** [bigmoby/fglair_for_homeassistant#80]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, since this morning I cannot reach all 3 of my AC units. 
I looked everywhere on the internet, but I cannot find any answer on the question: is there a cloud issue at this moment.

Why do I think this could be a cloud issue? I can control the units with the remotes, they work just fine. In the FGLAIR app, the units are offline. So, controlling via HA is therefore also not possible.

I checked my internet, rebooted all routers, switches etc... no result. Also, no issues at all with ay other device, only these 3 AC's.

I know this is basically not the place to ask this question and i apologies already.
But do any of you have issues like this? Is there indeed a cloud issue? Other suggestions?

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

**Comment by Chris370-arch** [comment]
I am seeing the same, the fglair also does not work so I'm going with it being a Fujitsu cloud problem that will fix itself at some point.

**Comment by jarube** [comment]
I've confirmation from several people (via Dutch forum on Tweakers.net) that they have same kind of problems.
So I guess the problem is in the cloud.

@bigmoby Shall I close this one or do you want to keep it open for others running into the same issue?

**Comment by Mertensk** [comment]
Indeed here in Belgium same problem, server down. FGLair app not responding either. Oldschool remote to the rescue.

**Comment by chiefcomm** [comment]
Interesting this must be affecting only the EU cloud as my setup in Australia using US cloud is unaffected.

**Comment by Yakie996** [comment]
mine now work via the fglair app but they are not via the HA, maybe it takes more time to restore or they did an upgrate?

**Comment by bigmoby** [comment]
Hi guys, yesterday evening I was affected by fglair down too (mine is UE located). Please let keep this issue open in order to monitor it. I suspect that now, after the asynchronous implementation, the integration is considered too aggressive in terms of cloud request. Probably we should reduce the update request polling...I should investigate it.

**Comment by jarube** [comment]
just now I was able to connect all three AC's with the app and I can indeed control them via APP and Home Assistant. So, it looks like the issue is solved... I'm still waiting for a reply from Fujitsu on my question to them yesterday.

Is everything working for you also?

**Comment by jarube** [comment]
> Hi @jarube , sorry, are you waiting for this question: `@bigmoby Shall I close this one or do you want to keep it open for others running into the same issue?` ?

Not sure what you mean, but do you want me to close this task?

**Comment by bigmoby** [comment]
Hi @jarube ,
no, `Please let's keep this issue open in order to monitor it. `

**Comment by jarube** [comment]
> Hi @jarube , no, `Please let's keep this issue open in order to monitor it. `

ok, no problem

**Comment by jarube** [comment]
The following was posted on a Dutch forum i mentioned earlier:

I contacted supplier. There appears to have been a major malfunction with the FGLair app this week, but it should now work again.
In my case (can be accessed via WiFi but not via external (mobile phone)) it is recommended to disconnect the system from power for 10 minutes and then switch it on again. Then the unit is registered and everything should be fine again.

_Translation by Google Translate_

**Comment by bigmoby** [comment]
Ok guys, so I think we could close this issue now.
