### ISSUE TITLE
nothing after login

### ISSUE THREAD

**Issue by Primaxionchris** [bigmoby/fglair_for_homeassistant#86]
### System Health details

Home Assistant with HACS. 

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After entering my login and password, I do not see any material uploaded. However, I chose EU as the region and the login and password were accepted.

On the FG Lair application, however, I have my 5 modules.

### Reproduction steps

1.Add plugin on HACS
2.ADD device from this plugin
3.Enter login/password and EU region 

### Debug logs

```text
I don’t know where I can find logs.
```

**Comment by tommentor85** [comment]
Hello!

Same issue here, this is what i found in log:
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:573
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 1:00:33 AM (5 occurrences)
Last logged: 1:00:33 AM

fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 377, in async_update
    await self._fujitsu_device.async_get_display_temperature_degree()
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/splitac.py", line 294, in async_get_display_temperature_degree
    display_temperature_value = self._display_temperature["value"]
                                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'value'
```
The 0.2.7 version works perfect. I have problem at 0.3.4 version ( I cleared everything from configuration.yaml what related to 0.2.7 version)

Thanks for help in advance!

**Comment by hessonam** [comment]
I have the same issue as above. US region. Was on version 0.2.7 which was working, but this one fails with the same error as above.

**Comment by bigmoby** [comment]
I'll try to understand in the next days

**Comment by bigmoby** [comment]
This issue duplicates https://github.com/bigmoby/fglair_for_homeassistant/issues/107
