### ISSUE TITLE
Unable to change HVAC modes

### ISSUE THREAD

**Issue by fati78** [bigmoby/fglair_for_homeassistant#9]
Hello,

I have been testing this integration for some weeks and its working fine for monitoring and changing the temperature set point and i am very grateful for that!

Now i have started implementing some automations for altering target temperature, turn ON or OFF and changing HVAC modes.
I am using available Services in hassio like
Climate: Set_temperature
Climate: Turn_off
Climate: Turn_on
Climate: Set HVAC_mode

Set_temperature and Turn_off is working but not the other two. HVAC mode can be changed to "Fan only" mode but it can not be changed back to "Heat" mode. If the AC is turned off then i need to use FGLAIR app or remote control to switch it on.

Anyone else with the same issue?
The easiest way to test is by going thorough the side bar "Development tools", click on the SERVICES tab, select one of the Climate services and click on CALL SERVICE button.
Thanx in advance! 

Using latest Hassio update RPi3-64

**Comment by mintnl** [comment]
Same problem here. Integration working fine except for "turn on".

**Comment by chiefcomm** [comment]
Hmmm interesting experience not something I face, I suggest capturing logs and lets see if we can figure it out.   Add the following to your config.

````
logger:
  default: critical
  logs:
    custom_components.fglair_heatpump_controller.climate: debug
    homeassistant.components.climate: debug
